/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/hLzwqZdDWYY
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Tenor_Sans } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

tenor_sans({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client"
import { Dialog, DialogTrigger, DialogContent } from "@/components/ui/dialog"
import Image from "next/image"
import React from "react"

export default function Gallery() {
    const images = ['image1', 'image2', 'image3', 'image4']
    const [src, setSrc] = React.useState("")
    return (
        <div className="max-w-6xl mx-auto px-4 py-12 sm:px-6 lg:px-8">
            <div className="text-center space-y-4">
                <h1 className="text-4xl font-bold tracking-tight text-gray-900 dark:text-gray-100">Stunning Gallery</h1>
                <p className="max-w-3xl mx-auto text-lg text-gray-500 dark:text-gray-400">
                    Explore our collection of breathtaking images that capture the beauty of the world around us.
                </p>
            </div>
            <div className="mt-12 grid grid-cols-1 gap-y-12 sm:grid-cols-2 sm:gap-x-6 lg:grid-cols-3 lg:gap-x-8">
                {
                    [...images, ...images].map((src, i) => (
                        <Dialog key={i}>
                            <DialogTrigger asChild onClick={() => {
                                setSrc(src)
                            }}>
                                <div className="group cursor-pointer overflow-hidden rounded-lg">
                                    <Image
                                        src={"/" + src + ".jpg"}
                                        alt={src}
                                        width="400"
                                        height="300"
                                        className="w-full h-full object-cover transition-transform duration-300 ease-in-out group-hover:scale-105"
                                        style={{ aspectRatio: "400/300", objectFit: "cover" }}
                                    />
                                    <div className="mt-3 text-center">
                                        <h3 className="text-lg font-medium text-gray-900 dark:text-gray-100">Serene Landscape</h3>
                                        <p className="mt-1 text-sm text-gray-500 dark:text-gray-400">
                                            A tranquil scene of rolling hills and a peaceful lake.
                                        </p>
                                    </div>
                                </div>
                            </DialogTrigger>
                            <DialogContent className="p-6 max-w-2xl">
                                <div className="flex flex-col items-center">
                                    <Image
                                        src={"/" + src + ".jpg"}
                                        alt={src}
                                        width="800"
                                        height="600"
                                        className="w-full h-auto object-cover rounded-lg"
                                        style={{ aspectRatio: "800/600", objectFit: "cover" }}
                                    />
                                    <div className="mt-4 text-center">
                                        <h3 className="text-xl font-medium text-gray-900 dark:text-gray-100">Serene Landscape</h3>
                                        <p className="mt-1 text-sm text-gray-500 dark:text-gray-400">
                                            A tranquil scene of rolling hills and a peaceful lake.
                                        </p>
                                    </div>
                                </div>
                            </DialogContent>
                        </Dialog>
                    ))
                }


            </div>
        </div>
    )
}
